service: btctrader

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'} 
#  region: us-east-1
  environment:
    API_URL: ${file(env.yml):${self:provider.stage}.API_URL}
    API_KEY: ${file(env.yml):${self:provider.stage}.API_KEY}
    API_SECRET: ${file(env.yml):${self:provider.stage}.API_SECRET}
    API_PASSPHRASE: ${file(env.yml):${self:provider.stage}.API_PASSPHRASE}

functions:
  maketrade:
    description: "Buys Bitcon Every Day"
    handler: handler.maketrade
    events:
      - schedule: 
          rate: cron(0 9 ? * * *)
          name: bitcon-buyer-${opt:stage, 'dev'}
          description: "Buys $5 Bitcon Every Day"
